spring.application.name=warframe-crafting-api

# enables logging the generated SQL queries from JPA to the console
spring.jpa.show-sql=true
# formatting the logged queires for ehanced readibility
spring.jpa.properties.hibernate.format_sql=true

# enables the H2 Console so we can see the tables
spring.h2.console.enabled=true

# make sure data.sql doesn't try to run before the database is actually built
spring.jpa.defer-datasource-initialization=true