spring.application.name=warframe-crafting-api

# enables logging of the generated SQL queries from JPA/Hibernate to the console
spring.jpa.show-sql=true
# formatting the logged queires for ehanced readibility
spring.jpa.properties.hibernate.format_sql=true